In [182]:
import pandas as pd
import numpy as np
from datetime import datetime

In [183]:
timeline = datetime.now().strftime("%Y%m%d%H%M%S")

# Extract

In [184]:
df = pd.read_csv('data/global_freelancers_raw.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   freelancer_ID        1000 non-null   object 
 1   name                 1000 non-null   object 
 2   gender               1000 non-null   object 
 3   age                  970 non-null    float64
 4   country              1000 non-null   object 
 5   language             1000 non-null   object 
 6   primary_skill        1000 non-null   object 
 7   years_of_experience  949 non-null    float64
 8   hourly_rate (USD)    906 non-null    object 
 9   rating               899 non-null    float64
 10  is_active            911 non-null    object 
 11  client_satisfaction  824 non-null    object 
dtypes: float64(3), object(9)
memory usage: 93.9+ KB


# Transform

In [185]:
df.columns = df.columns.str.strip().str.replace(' ', '_').str.replace('(', '').str.replace(')', '').str.lower()
df.head()

freelancer_id             name  gender   age    country language  \
0      FL250001  Ms. Nicole Kidd       f  52.0      Italy  Italian   
1      FL250002   Vanessa Garcia  FEMALE  52.0  Australia  English   
2      FL250003      Juan Nelson    male  53.0    Germany   German   
3      FL250004   Amanda Spencer       F  38.0  Australia  English   
4      FL250005  Lynn Curtis DDS  female  53.0    Germany   German   

            primary_skill  years_of_experience hourly_rate_usd  rating  \
0  Blockchain Development                 11.0             100     NaN   
1             Mobile Apps                 34.0         USD 100     3.3   
2          Graphic Design                 31.0              50     0.0   
3         Web Development                  4.0             $40     1.5   
4         Web Development                 27.0              30     4.8   

  is_active client_satisfaction  
0         0                 NaN  
1         1                 84%  
2         N                 71%  
3         N                 90%  
4         0                 83%

### Freelancer_id

In [186]:
df.dropna(subset=['freelancer_id'], inplace=True)
df.shape

(1000, 12)

### Gender

In [187]:
df['gender'].unique()

array(['f', 'FEMALE', 'male', 'F', 'female', 'm', 'MALE', 'Female', 'M',
       'Male'], dtype=object)

In [188]:
df['gender'] = df['gender'].replace(['M', 'm', 'MALE', 'Male'], 'male')
df['gender'] = df['gender'].replace(['F', 'f', 'FEMALE', 'Female'], 'female')
df['gender'].unique()

array(['female', 'male'], dtype=object)

### Country

In [189]:
df['country'].unique()

array(['Italy', 'Australia', 'Germany', 'Netherlands', 'Indonesia',
       'United States', 'Turkey', 'United Kingdom', 'Argentina', 'Japan',
       'India', 'Brazil', 'South Korea', 'Russia', 'Canada', 'France',
       'Egypt', 'South Africa', 'China', 'Mexico', 'Spain'], dtype=object)

### Language

In [190]:
df['language'].unique()

array(['Italian', 'English', 'German', 'Dutch', 'Indonesian', 'Turkish',
       'Spanish', 'Japanese', 'Hindi', 'Portuguese', 'Korean', 'Russian',
       'French', 'Arabic', 'Afrikaans', 'Mandarin'], dtype=object)

### Primary Skill

In [191]:
df['primary_skill'].unique()

array(['Blockchain Development', 'Mobile Apps', 'Graphic Design',
       'Web Development', 'AI', 'Data Analysis', 'UI/UX Design',
       'Cybersecurity', 'DevOps', 'Machine Learning'], dtype=object)

### Years of Experience

In [192]:
df['years_of_experience'].unique()

array([11., 34., 31.,  4., 27., 14., 10., 22., 17., 15., 18., 20.,  0.,
       13., nan,  3.,  9., 21.,  8., 19., 32., 28.,  6., 23.,  7.,  1.,
       33., 16., 35., 12., 38.,  5., 30.,  2., 25., 39., 29., 40., 26.,
       24., 37., 41.])

In [193]:
df['years_of_experience'] = df['years_of_experience'].fillna(0)
df['years_of_experience'].isna().sum()

np.int64(0)

### Hourly Rate USD

In [194]:
df['hourly_rate_usd'].unique()

array(['100', 'USD 100', '50', '$40', '30', '$30', 'USD 75', 'USD 40',
       nan, '$50', '40', '75', 'USD 50', 'USD 30', '$20', '20', '$75',
       '$100', 'USD 20'], dtype=object)

In [195]:
df['hourly_rate_usd'] = df['hourly_rate_usd'].astype(str).str.replace(r'[^0-9.]', '', regex=True).replace('', np.nan).astype(float)
df['hourly_rate_usd'].unique()

array([100.,  50.,  40.,  30.,  75.,  nan,  20.])

### Rating

In [196]:
df['rating'].unique()

array([nan, 3.3, 0. , 1.5, 4.8, 2.4, 3.1, 4.6, 4. , 3.6, 2. , 2.9, 3.7,
       1.2, 2.5, 1.1, 1.8, 4.7, 1.3, 1. , 4.2, 1.4, 2.2, 3.2, 2.7, 2.8,
       4.9, 4.5, 1.9, 3.4, 2.3, 3.9, 3.5, 4.4, 2.6, 1.6, 3.8, 1.7, 5. ,
       3. , 4.1, 4.3, 2.1])

### Is Active

In [197]:
df['is_active'].unique()

array(['0', '1', 'N', 'False', 'True', 'yes', 'Y', nan, 'no'],
      dtype=object)

In [198]:
df['is_active'] = (
    df['is_active']
    .replace(['1', 'Y', 'True', 'yes'], True)
    .replace(['0', 'N', 'False', 'no'], False)
    .astype(bool)
)

df['is_active'].unique()

array([False,  True])

### Client Satisfaction

In [199]:
df['client_satisfaction'].unique()

array([nan, '84%', '71%', '90%', '83%', '94%', '76%', '77%', '86%', '93%',
       '70%', '69%', '60%', '87%', '75%', '68%', '65%', '100%', '92',
       '89%', '62%', '82', '81%', '63%', '67%', '80%', '74%', '85%',
       '79%', '72%', '64', '88', '96%', '96', '81', '61%', '97%', '64%',
       '73%', '88%', '72', '92%', '82%', '93', '83', '78', '95%', '80',
       '87', '66%', '78%', '68', '91%', '97', '60', '70', '99%', '76',
       '86', '95', '74', '100', '73', '67', '77', '98%', '71', '85', '91',
       '94', '84', '90', '62', '65', '75', '63', '61', '66', '99', '79',
       '69', '89'], dtype=object)

In [200]:
df['client_satisfaction'] = df['client_satisfaction'].astype(str).str.replace(r'[^0-9.]', '', regex=True).replace('', np.nan).astype(float)
df['client_satisfaction'].unique()

array([ nan,  84.,  71.,  90.,  83.,  94.,  76.,  77.,  86.,  93.,  70.,
        69.,  60.,  87.,  75.,  68.,  65., 100.,  92.,  89.,  62.,  82.,
        81.,  63.,  67.,  80.,  74.,  85.,  79.,  72.,  64.,  88.,  96.,
        61.,  97.,  73.,  78.,  95.,  66.,  91.,  99.,  98.])

In [201]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   freelancer_id        1000 non-null   object 
 1   name                 1000 non-null   object 
 2   gender               1000 non-null   object 
 3   age                  970 non-null    float64
 4   country              1000 non-null   object 
 5   language             1000 non-null   object 
 6   primary_skill        1000 non-null   object 
 7   years_of_experience  1000 non-null   float64
 8   hourly_rate_usd      906 non-null    float64
 9   rating               899 non-null    float64
 10  is_active            1000 non-null   bool   
 11  client_satisfaction  824 non-null    float64
dtypes: bool(1), float64(5), object(6)
memory usage: 87.0+ KB


### `dim_genders`

In [202]:
dim_genders = df[['gender']].dropna().drop_duplicates().reset_index(drop=True)
dim_genders['gender_id'] = range(1, len(dim_genders) + 1)
dim_genders = dim_genders[['gender_id', 'gender']]
dim_genders

gender_id  gender
0          1  female
1          2    male

### `dim_countries`

In [203]:
dim_countries = df[['country']].dropna().drop_duplicates().reset_index(drop=True)
dim_countries['country_id'] = range(1, len(dim_countries) + 1)
dim_countries = dim_countries[['country_id', 'country']]
dim_countries

country_id         country
0            1           Italy
1            2       Australia
2            3         Germany
3            4     Netherlands
4            5       Indonesia
5            6   United States
6            7          Turkey
7            8  United Kingdom
8            9       Argentina
9           10           Japan
10          11           India
11          12          Brazil
12          13     South Korea
13          14          Russia
14          15          Canada
15          16          France
16          17           Egypt
17          18    South Africa
18          19           China
19          20          Mexico
20          21           Spain

### `dim_languages`

In [204]:
dim_languages = df[['language']].dropna().drop_duplicates().reset_index(drop=True)
dim_languages['language_id'] = range(1, len(dim_languages) + 1)
dim_languages = dim_languages[['language_id', 'language']]
dim_languages

language_id    language
0             1     Italian
1             2     English
2             3      German
3             4       Dutch
4             5  Indonesian
5             6     Turkish
6             7     Spanish
7             8    Japanese
8             9       Hindi
9            10  Portuguese
10           11      Korean
11           12     Russian
12           13      French
13           14      Arabic
14           15   Afrikaans
15           16    Mandarin

### `dim_primary_skills`

In [205]:
dim_primary_skills = df[['primary_skill']].dropna().drop_duplicates().reset_index(drop=True)
dim_primary_skills['primary_skill_id'] = range(1, len(dim_primary_skills) + 1)
dim_primary_skills = dim_primary_skills[['primary_skill_id', 'primary_skill']]
dim_primary_skills

primary_skill_id           primary_skill
0                 1  Blockchain Development
1                 2             Mobile Apps
2                 3          Graphic Design
3                 4         Web Development
4                 5                      AI
5                 6           Data Analysis
6                 7            UI/UX Design
7                 8           Cybersecurity
8                 9                  DevOps
9                10        Machine Learning

### `fact_freelancers`

In [206]:
fact_freelancers = df.merge(dim_genders, on='gender', how='left') \
    .merge(dim_countries, on='country', how='left') \
    .merge(dim_languages, on='language', how='left') \
    .merge(dim_primary_skills, on='primary_skill', how='left')

fact_freelancers = fact_freelancers[['freelancer_id', 'name', 'gender_id', 'country_id', 'language_id', 'primary_skill_id', 'years_of_experience', 'hourly_rate_usd', 'rating', 'client_satisfaction', 'is_active']]
fact_freelancers

freelancer_id             name  gender_id  country_id  language_id  \
0        FL250001  Ms. Nicole Kidd          1           1            1   
1        FL250002   Vanessa Garcia          1           2            2   
2        FL250003      Juan Nelson          2           3            3   
3        FL250004   Amanda Spencer          1           2            2   
4        FL250005  Lynn Curtis DDS          1           3            3   
..            ...              ...        ...         ...          ...   
995      FL250996    Albert Wilcox          2           7            6   
996      FL250997    Cheryl Norris          1           3            3   
997      FL250998    Kathy Watkins          1          10            8   
998      FL250999      John Obrien          2          14           12   
999      FL251000       Dawn Green          1          20            7   

     primary_skill_id  years_of_experience  hourly_rate_usd  rating  \
0                   1                 11.0            100.0     NaN   
1                   2                 34.0            100.0     3.3   
2                   3                 31.0             50.0     0.0   
3                   4                  4.0             40.0     1.5   
4                   4                 27.0             30.0     4.8   
..                ...                  ...              ...     ...   
995                 9                 13.0            100.0     0.0   
996                 1                  6.0             40.0     2.8   
997                 6                 15.0             75.0     NaN   
998                10                 22.0            100.0     2.8   
999                 7                 18.0             20.0     1.7   

     client_satisfaction  is_active  
0                    NaN      False  
1                   84.0       True  
2                   71.0      False  
3                   90.0      False  
4                   83.0      False  
..                   ...        ...  
995                 68.0      False  
996                 82.0      False  
997                 94.0      False  
998                 97.0       True  
999                 72.0       True  

[1000 rows x 11 columns]

# Load

In [207]:
dim_genders.to_csv(f'target/dim_genders_{timeline}.csv', index=False)
dim_countries.to_csv(f'target/dim_countries_{timeline}.csv', index=False)
dim_languages.to_csv(f'target/dim_languages_{timeline}.csv', index=False)
dim_primary_skills.to_csv(f'target/dim_primary_skills_{timeline}.csv', index=False)
fact_freelancers.to_csv(f'target/fact_freelancers_{timeline}.csv', index=False)